### ISSUE TITLE
loading documents in to Chroma: KILLED

### ISSUE THREAD

**Issue by alanesq** [amscotti/local-LLM-with-RAG#1]
I am attempting to run this on my Linux Mint laptop core i5.
All seems to go well until I try running   "python app.py"
It seems to read in the PDF documents ok but when it comes to "loading documents in to Chroma" after  a few seconds it just exits with a message "Killed"

i.e.
100%|█████████████████████████████████████████████| 4/4 [00:06<00:00,  1.59s/it]
Loading documents into Chroma
Killed

BTW - Thanks for publishing this, it looks like exactly what  have been looking for :-)

**Comment by amscotti** [comment]
Interesting, I only tested this on my Macbook but I can give it a try later tonight on my Linux system to see what is going on.

If I had to guess, it's something with the `JinaAIEmbeddings` code. I already had the model downloading from Huggingface before I moved the code into it's own class, so maybe there is any issue when trying to download the model on the first run.

One way to test this is to temporarily switch to another embedding service, like OpenAI like so,

```
from langchain.embeddings.openai import OpenAIEmbeddings

db = Chroma.from_documents(documents, OpenAIEmbeddings())
```
(with the `OPENAI_API_KEY` set)

This would at least pinpoint the issue.

**Comment by amscotti** [comment]
Another thing you can try is running the embedding on the CPU, trying this on a new system with less specs than my laptop I get `out of memory` issue.  You can update `device_map="auto"` to `device_map="cpu"`, in the `JinaAIEmbeddings` class. This will make it take **_much longer_**, as the GPU would be a lot faster but it still should work.

**Comment by alanesq** [comment]
Thanks for the replies.
After some more playing today I suspect  the main issue is my computer is just not powerful enough to do this?
I only have 8gb ram and no GPU.  I may look at getting something a bit more suitable....

**Comment by amscotti** [comment]
Yeah, I think the way the project is set up right now. It requires a bit more memory. [mistral](https://ollama.ai/library/mistral) can run on 8gb of ram, but I think creating the embedding is the main issue.

If you want to keep playing around with this project here's a couple things you can try,
- You could use an external embeddings service like OpenAI, project wouldn't be 100% local any more but the main part of it would.
- Find a smaller embeddings model on Huggingface that requires less resources, of course this may affect the performance of the lookups.
- Creating embedding one at a time instead of all at once, would take longer, but I **_believe_** this would useless memory.

Hopefully something works out for you. I don't think there's anything else I can do, so I'm going to close this issue.

Also, thanks for your interest in the project. 😄
