### ISSUE TITLE
I asked a question in Chinese and the answer was English

### ISSUE THREAD

**Issue by weirdo2310** [amscotti/local-LLM-with-RAG#10]
Hi, I use Langchain to upload Chinese documents, but when I ask a question in Chinese, the answer language becomes English. I want it to answer me in Chinese. Where should I start with the code? Also, its answers aren't based on what I've uploaded.
![屏幕截图 2024-06-05 155052](https://github.com/amscotti/local-LLM-with-RAG/assets/66229572/2d44f73e-d991-4206-9cd4-9ef845630f74)
My coding ability is limited, in the code you provided, I debug for a long time but did not solve this problem, can you give me some ideas? Thank you very much!
And can I use the offline model downloaded locally instead of Ollama?

**Comment by amscotti** [comment]
You have a couple of questions here so let me break them down one by one.

### Responding in Chinese (or any non-English)
This would take some experimenting, but I would start by updating the prompt found [here](https://github.com/amscotti/local-LLM-with-RAG/blob/main/llm.py#L21) to reply in the same language that the question was asked in. This would depend on a couple of things, but mostly on how capable the model is at following instructions. You may need to even repeat this instruction with something like "IMPORTANT: ".

### In accurate answers for non-English documentation
There could be a couple of different things going on here, the large language model capability of understanding Chinese, and the embedding model ability on Chinese text. For the LLM, by default, this is using `mistral` which I don't think has much training on Chinese text, I would try [Qwen](https://ollama.com/library/qwen) or [Yi](https://ollama.com/library/yi) to see if they improve accuracy, and as far as an embedding model the default is `nomic-embed-text`, but I'm not sure how it performs on Chinese text and I don't know any other ones to recommend. I know you can use an LLM for embedding text with Ollama, but I've never seen this yield good performance from my testing but it may be worth testing in this case.

Different options for the LLM and embedding model can be set at the command prompt without needing to update the code, as long as the models come from Ollama.

###  Local Model instead of Ollama
Everything in the application is built to use the Ollama SDK right now, but as it's using LangChain you could update the code to use another local model system that is supported by LangChain. It's doable, but it will take a fair amount of work to update the code to be able to do this. You would have to remove a lot of the code dealing with Ollama SDK to check if the model is available and update all the LangChain code using Ollama. You should be able to leave the prompts and most other code alone, you just need to load the other LLMs using LangChain.

**Comment by weirdo2310** [comment]
Your reply is very important to me, thank you very much! I tried to update the prompt and emphasized that the answer should be in Chinese, but the result of this method of updating the prompt was generally, and the answer would still be in English. 

**Another question is, is the response not based on the database generated from uploaded documents, but derived from web documents, referring to Sources, also relevant to LLM?**
![image](https://github.com/amscotti/local-LLM-with-RAG/assets/66229572/2fb91297-7084-4a38-ba65-f89b80037c71)


**In addition, I have tested the running time of generating the answer, and it feels that the time of loading embedding is very long. Is there any way to optimize the time?**
![image](https://github.com/amscotti/local-LLM-with-RAG/assets/66229572/06049066-214e-405d-9ef4-18454dffd0fc)

![image](https://github.com/amscotti/local-LLM-with-RAG/assets/66229572/d73963ae-399b-476d-8c9b-4c98bfe5f7aa)

**Comment by amscotti** [comment]
## Answer still in English
Without seeing how you change the prompt, it's hard to give additional comments, but as I mentioned before, it's very dependent on the model’s ability to follow instructions, with the additional context. This would fall under Prompt Engineering techniques. Again, one thing you could try is repeating the instruction at the end of the prompt with something like “IMPORTANT: Ensure that you only reply in Chinese”. Another thing you could try is converting the English prompt into Chinese. This is also very dependent upon the model’s ability to understand Chinese.

## Response not based on the database generated
Generally, the response will only be based on documents looted into the vector database, but again it's really up to the model’s ability to follow instructions. In the prompt, it's instructed not to answer if there is no context from the research but as this is an LLM, it has the capability of skipping that instruction and providing research from its own knowledge. I truly have not tested this with any foreign language, so I have no idea how this would work at all. I imagine the embedding is not optimized for Chinese and items are being returned that are not relevant to your query, but I'm not 100% sure.

##  Time of loading embedding
The code in your screenshot is not the code that is loading embeddings of the documents into the database, but embedding your query and running inference on the model, which is why it takes so long. If you wish to speed this up, you can
- Get a better graphics card, The Nvidia 4000 series should perform well, depending on the size of the model.
- Use a smaller model, the default model is 7B, but there are smaller models available, that will run faster, but be less capable.


As I don't speak any foreign language (really wish I did) it's very hard for me to test this used case, but I will also remind you that this project is simply an experiment to demonstrate how to use RAG techniques locally with Ollama. If you want to continue working on this, I highly suggest looking for a model that has been trained on Chinese text as I mentioned in my first reply, and applying Prompt Engineering techniques to improve the LLM's output.

**Comment by weirdo2310** [comment]
Thanks for your reply. I replaced the model and generated answers much better than before. Replacing the model and repeating "only Chinese responses" in the prompt worked. I am now guessing that the reason for the slow answer generation may not be the embedding model, but the **Vector Similarity** process, but I don't know how to optimize the answer generation speed. On top of that, your code has been extremely helpful to me! Thank you so much for sharing!

**Comment by amscotti** [comment]
Happy to hear that you've been successful in improving things and that you have found this code helpful. Best of luck.
