### ISSUE TITLE
[discussion] Nice project

### ISSUE THREAD

**Issue by XenocodeRCE** [amscotti/local-LLM-with-RAG#3]
Hello, really nice project I was about to do the same PoC !

Here it works, for the app.py it uses 16GB of RAM (i have 28) and the GPU works fine (A4500)

1. Wouldn't it be better to vectorize the PDFs in a routine, so the process would be quicker ? Or a sort of "cache" for the vectorized data
2. Can we use other ollama models ? Gemma seems very dumb for me, it refuses to answer a lot of stuff and keeps telling me it is only an LLM model. I usually have really convincing results with mistral / mixtral

**Comment by amscotti** [comment]
Hello! Thanks, I'm happy to hear that someone has found this example useful. :) The main focus of this code is just to experiment and provide an example of being able to run everything locally. I honestly haven't put too much consideration into anything besides creating a POC.

## Number 1: Vectorize the PDFs
Yes, needing to re-create the vectors isn't ideal for any serious application. However, for testing and tweaking things, it's quite nice as it lets you reset everything with each run.

If you wanted to take this idea and expand upon it, I would recommend running the vector database separately from the application and having a separate process dedicated to indexing the PDFs.  This would allow you to focus on finding the best method for chunking the PDFs for the desired use case. I would also explore additional embedding models. Although I think Jina AI's embedding models do quite well, using a larger model would likely give you better results since the majority of the time is spent indexing the PDF chunks and not embedding the query. This approach would make indexing a one-time operation (until you wanted to re-index items).

## Number 2: Other Ollama models
Absolutely! Until recently, I used Mistral, and it was working nicely with pretty good answers. With my [latest commit](https://github.com/amscotti/local-LLM-with-RAG/commit/a3cc163954b7fe1e78014c8c62b55461f6020fb1), I wanted to improve speed, so I switched to a smaller embedding model and Gemma 2B instead of Mistral 7B. Speed definitely increased, but the quality of the answers did go down slightly. Still, the smaller model was able to answer my test questions, just without as much detail. If I want to refine this a bit more, I would probably update the prompt or go back to Mistral.

A nice enhancement for this project might be the ability to specify the model's name from the command-line argument. The Ollama library could then pull down that model if it's not already present. This would make testing different models easier.

**Comment by amscotti** [comment]
I've made some updates to the project which I think are in line with what you're asking about.

Now you can ask multiple questions without recreating the embedding or loading the documents again.

I've also added command-line arguments to be able to select different models available to Ollama, and set the default back to Mistral. The application will attempt to download the models if they're not available locally.

**Comment by kalle07** [comment]
Hey, iam only a stupid user   ;)

what is better in RAG than "pdfgear"
https://www.pdfgear.com/de/
its 300MB (offline) and better and faster than all i tryed before ... (privateGPT, GPT4all and Khoj ...)

how you prevent in your software that the model is halucinating an tell somwhat that the model knows but its not based on the document, i allways had that impression!
PDFgear says "i dont found it" or "you are shure you talk about that document" ...

**Comment by amscotti** [comment]
@kalle07 I've never used pdfgear before, but I imagine professional software would be a bit than better this project, because this project is just an example mostly for learning purposes and experimentation. I would suggest to use whatever works best for you, but if you're interested in experimenting and learning more about RAG, this is a good starting point. I seem that "pdfgear" is focused on just PDFs, but [LangChain](https://www.langchain.com/) (The library this tool is build with) has loaders for many different formats including PDFs, but much more.

With any language model, you have the capability of having hallucinations. This project is relying upon the prompt answer the question from the provided research, but this will not 100% prevent hallucinations. In my testing it will return that it is unable to answer the question if no research was found in the database, but with the way that vector databases work if you increase the number of documents, you may have irrelevant documents returned that the language model may try to answer your question with and provide you the wrong answer. The topic of RAG is large with many different techniques to help avoid hallucinations, but I would say any tool that can point to it's source for answering your question would be a step in the right direction.

Again, I've never used "pdfgear" before but if it's only looking at a single PDF it would be simpler to avoid hallucinations as it would be able to know if there is something or nothing relevant to your question in a single PDF.

**Comment by kalle07** [comment]
thy for the explanation...

maybe i try yours if it give a small Gui    ;)
